version: "3.9"
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile  # Dockerfile 이름
    image: parkingissue-db:1.1.4  # 빌드될 이미지 이름
    container_name: parkingissue_database
    env_file:
      - .db_env
    ports:
      - "6033:3306"  # 호스트 포트:컨테이너 포트
    volumes:
      - ./../data:/var/lib/mysql  # 데이터 지속성을 위한 볼륨 마운트
